steps:
  # Install deps
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', '/workspace/rss-mail-summarizer/requirements.txt', '--target', '/workspace']
  
  # Test mastodon_connector_activate locally inside build
  - name: 'python:3.11'
    entrypoint: python
    args: ['-c', 'import main; main.mastodon_connector_activate()']
    env:
      - 'PYTHONPATH=/workspace:/workspace/rss-mail-summarizer'
      - 'PROJECT_ID=dhbw-projekt-467419'

  # Test rss_mail_summarizer_main locally inside build
  - name: 'python:3.11'
    entrypoint: python
    args: ['-c', 'import main; main.main()']
    env:
      - 'PYTHONPATH=/workspace:/workspace/rss-mail-summarizer'
      - 'PROJECT_ID=dhbw-projekt-467419'

  # Deploy mastodon_connector
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - mastodon_connector
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=/workspace/rss-mail-summarizer
      - --entry-point=mastodon_connector_activate
      - --trigger-http
      - --allow-unauthenticated
      - --memory=2GiB
      - --timeout=120s
      - --set-env-vars
      - PROJECT_ID=dhbw-projekt-467419

  # Deploy rss_mail_summarizer_main
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - rss_mail_summarizer_main
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=/workspace/rss-mail-summarizer
      - --entry-point=main
      - --trigger-http
      - --allow-unauthenticated
      - --memory=2GiB
      - --timeout=120s
      - --set-env-vars
      - PROJECT_ID=dhbw-projekt-467419

options:
  logging: CLOUD_LOGGING_ONLY