steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        SECRET=$(gcloud secrets versions access latest --secret="MY_SECRET_NAME")
        gcloud functions deploy rss_mail_summarizer_main \
          --entry-point=main \
          --runtime=python311 \
          --trigger-http \
          --allow-unauthenticated \
          --source=./rss_mail_summarizer \
          --region=europe-west3 \
          --memory=2GiB \
          --timeout=120s \
          --set-env-vars=MY_SECRET=$SECRET

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        SECRET=$(gcloud secrets versions access latest --secret="MY_SECRET_NAME")
        gcloud functions deploy mastodon_connector \
          --entry-point=fetch_and_store_mastodon_links \
          --runtime=python311 \
          --trigger-http \
          --allow-unauthenticated \
          --source=./rss_mail_summarizer \
          --region=europe-west3 \
          --memory=2GiB \
          --timeout=120s \
          --set-env-vars=MY_SECRET=$SECRET

options:
  logging: CLOUD_LOGGING_ONLY