steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - rss_mail_summarizer_main
      - --entry-point=main
      - --runtime=python311
      - --trigger-http
      - --allow-unauthenticated
      - --source=./rss_mail_summarizer
      - --region=europe-west3
      - --memory=2GiB
      - --timeout=120s

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - mastodon_connector
      - --entry-point=fetch_and_store_mastodon_links
      - --runtime=python311
      - --trigger-http
      - --allow-unauthenticated
      - --source=./rss_mail_summarizer
      - --region=europe-west3
      - --memory=2GiB
      - --timeout=120s

options:
  logging: CLOUD_LOGGING_ONLY