steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  secretEnv: ['MY_SECRET']
  args:
    - -c
    - |
        --entry-point=main \
        --runtime=python311 \
        --trigger-http \
        --allow-unauthenticated \
        --source=./rss_mail_summarizer \
        --region=europe-west3 \
        --memory=2GiB \
        --timeout=120s

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  secretEnv: ['MY_SECRET']
  args:
    - -c
    - |
      gcloud functions deploy mastodon_connector \
        --entry-point=mastodon_connector_activate \
        --runtime=python311 \
        --trigger-http \
        --allow-unauthenticated \
        --source=./rss_mail_summarizer \
        --region=europe-west3 \
        --memory=2GiB \
        --timeout=120s

availableSecrets:
  secretManager:
  - versionName: projects/dhbw-projekt-467419/secrets/rss-firebase-key/versions/latest
    env: 'MY_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY