steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    secretEnv: ['MY_SECRET']
    args:
      - -c
      - |
        gcloud functions deploy rss_mail_summarizer_main \
          --entry-point=main \
          --runtime=python311 \
          --trigger-http \
          --allow-unauthenticated \
          --source=./rss_mail_summarizer \
          --region=europe-west3 \
          --memory=2GiB \
          --timeout=120s \
          --set-env-vars="MY_SECRET=${MY_SECRET}"

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    secretEnv: ['MY_SECRET']
    args:
      - -c
      - |
        gcloud functions deploy mastodon_connector \
          --entry-point=fetch_and_store_mastodon_links \
          --runtime=python311 \
          --trigger-http \
          --allow-unauthenticated \
          --source=./rss_mail_summarizer \
          --region=europe-west3 \
          --memory=2GiB \
          --timeout=120s \
          --set-env-vars="MY_SECRET=${MY_SECRET}"

availableSecrets:
  secretManager:
    - versionName: projects/PROJECT_ID/secrets/rss-firebase-key/versions/latest
      env: MY_SECRET

options:
  logging: CLOUD_LOGGING_ONLY