steps:
  # Install deps (optional but useful to validate requirements)
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', 'rss_mail_summarizer/requirements.txt', '--target', '/workspace']

  # Deploy mastodon_connector function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - mastodon_connector
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=./rss_mail_summarizer
      - --entry-point=mastodon_connector_activate
      - --trigger-http
      - --allow-unauthenticated
      - --memory=2GiB
      - --timeout=120s
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},LOG_LEVEL=DEBUG

  # Deploy rss_mail_summarizer_main function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    secretEnv: ['SENDER_EMAIL', 'RECIPIENT_EMAIL']
    args:
      - functions
      - deploy
      - rss_mail_summarizer_main
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=./rss_mail_summarizer
      - --entry-point=main
      - --trigger-http
      - --allow-unauthenticated
      - --memory=2GiB
      - --timeout=120s
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},SENDER_EMAIL=$$SENDER_EMAIL,RECIPIENT_EMAIL=$$RECIPIENT_EMAIL,LOG_LEVEL=DEBUG

  # Deploy call_alerts function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - call_alerts
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=./rss_mail_summarizer
      - --entry-point=call_alerts
      - --trigger-http
      - --allow-unauthenticated
      - --memory=2GiB
      - --timeout=120s
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},LOG_LEVEL=DEBUG

# Hier werden die Secrets verfügbar gemacht
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/sender-email/versions/latest
      env: 'SENDER_EMAIL'
    - versionName: projects/${PROJECT_ID}/secrets/recipient-email/versions/latest
      env: 'RECIPIENT_EMAIL'

options:
  logging: CLOUD_LOGGING_ONLY
